manager/urls.py
from django.urls import path
from .views import reservations_list, update_reservation

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservations_list, name='reservations_list'),
    path('reservations/update/<int:pk>/', update_reservation, name='update_reserve')
]

restaurant2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import logout, logout_view, login_view, registration_view


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),

    path('admin/', admin.site.urls),
    path('', include('base_app.urls', namespace='base_app')),

    path('manager/', include('manager.urls', namespace='manager'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from base_app.models import ModelFormRegistration
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator


def is_manager(user):
    return user.groups.filter(name='manager').exists()


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def reservations_list(request):
    registration = ModelFormRegistration.objects.filter(is_processed=False).order_by('date')

    paginator = Paginator(registration, 5)
    page = request.GET.get('page')
    registration = paginator.get_page(page)

    return render(request, 'reservations_list.html', context={'reg_list': registration})


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_reservation(request, pk):
    ModelFormRegistration.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:reservations_list')

manager/templates/reservations_list.html
{% extends 'index.html' %}


{% block content %}
    <section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% for item in reg_list %}
                    <div class="row">
                        <div class="col-md-3">
                            <a href="{% url 'manager:update_reserve' pk=item.pk %}">
                                <button type="button", class="btn-primary">Закрыть заявку</button>
                            </a>
                        </div>
                        <div class="col-md-3">{{ item.name }}</div>
                        <div class="col-md-3">{{ item.phone }}</div>
                        <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9"><p>{{ item.message }}</p></div>
                        <div class="col-md-3">{{ item.email }}</div>
                    </div>
                    <hr/>
                {% endfor %}
            </div>
        </div>
        <div id="navigation" class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if reg_list.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ reg_list.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for page in reg_list.paginator.page_range %}
                                {% if page == reg_list.number %}
                                    <li class="page-item active">
                                        <a class="page-link" href="#"> {{page}}
                                            <span class="sr-only">(current)</span>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{page}}">
                                            {{page}}
                                        </a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if reg_list.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ reg_list.paginator.num_pages }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </section>
{% endblock %}